trigger:
- '*'

pool:
  name: Default
  demands: Docker

resources:
  # https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-containers?view=azure-pipelines
  containers:
  - container: alpine
    # https://hub.docker.com/_/alpine
    image: alpine:latest

# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml
services:
  alpine: alpine

steps:
- script: echo "Hello World"
  target:
    container: alpine
