trigger:
- '*'

pool:
  name: Default
  demands: Docker

resources:
  containers:
  - container: sshd
    image: testcontainers/sshd:1.2.0
    ports:
    - 22:22

services:
  sshd: sshd

steps:
- script: netstat -aon
  displayName: 'List all ports'
